### PR TITLE
fix: Updates the base image used to enable the spellcheck

### PR DESCRIPTION
**Pull request by eugene-davis**
This version of the base image provides the underlying libraries used by Enchant.

### CODE REVIEW

**Comment by martinm82** [comment]
Do we actually need this change? Isn't the dependency already included in the requirements file?

**Comment by eugene-davis** [comment]
> Do we actually need this change? Isn't the dependency already included in the requirements file?

Just PyEnchant. Which connects to Enchant, which uses things like Aspell.

**Comment by martinm82** [comment]
> > Do we actually need this change? Isn't the dependency already included in the requirements file?
> 
> Just PyEnchant. Which connects to Enchant, which uses things like Aspell.

Oh, so pyenchant has some system dependencies?

**Comment by eugene-davis** [comment]
> > > Do we actually need this change? Isn't the dependency already included in the requirements file?
> > 
> > 
> > Just PyEnchant. Which connects to Enchant, which uses things like Aspell.
> 
> Oh, so pyenchant has some system dependencies?

Yes, that's actually why I mentioned I'd rather use something like scspell in the future (but that would be a separate step).

**Pull request merged**
